name: GH Actions Playground (with rust!!)
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  MY_ENV_VAR: 123abc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable corepack and install dependencies
        run: |
          corepack enable
          yarn

      - name: Install Wasm
        run: rustup target add wasm32-unknown-unknown

      - name: Build Rust worker
        run: cargo build --release --target=wasm32-unknown-unknown

      - name: Notify failure
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Install yarn
        run: |
          corepack enable
          yarn

      - name: Check branch name env var
        run: echo $BRANCH_NAME

      - name: Authenticate neon
        run: npx neonctl auth --api-key ${{ secrets.NEON_API_KEY }}

      - name: Check if neon branches exist
        run: npx neonctl branches list

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy target/wasm32-unknown-unknown/release/gh_actions_playground.wasm --name gh-actions-playground
