name: GH Actions Playground (with rust!!)
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable corepack and install dependencies
        run: |
          corepack enable
          yarn

      - name: Install Wasm
        if: false
        run: rustup target add wasm32-unknown-unknown

      - name: Build Rust worker
        if: false
        run: cargo build --release --target=wasm32-unknown-unknown

      - name: Notify failure
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Check branch name env var
        run: echo $BRANCH_NAME

      - name: Check if neon branches exist
        run: npx neonctl branches list --project-id ${{ secrets.NEON_PROJECT_ID }}

      - name: Echo What up
        id: what-up
        run: echo "message=\"What up\"" >> "$GITHUB_OUTPUT"

      - name: neonbranch
        id: neon-branch
        run: echo "NEON_BRANCH=$(npx neonctl branches list --project-id ${{ secrets.NEON_PROJECT_ID }} | grep $BRANCH_NAME | awk '{print $4}')" >> "GITHUB_OUTPUT"

      - name: Check github outputs
        run: |
          echo "What up output:"
          echo ${{ steps.what-up.outputs.message }}
          echo "Neon branch:"
          echo ${{ steps.neon-branch.outputs.NEON_BRANCH }}

      - name: Deploy
        if: false
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy target/wasm32-unknown-unknown/release/gh_actions_playground.wasm --name gh-actions-playground
