name: GH Actions Playground (with rust!!)
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VAR_1: ${{ vars.prod.VAR_1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Rust tool
        run: cargo build --release

      - name: My backup step
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Take a lap to see what is real
        run: env

      - name: Run this town
        run: ./target/release/gh-actions-playground --myvar=$VAR_1 --secret=${{secrets.SECRET_2}}
