name: GH Actions Playground (with rust!!)
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  MY_ENV_VAR: 123abc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Rust tool
        run: cargo build --release

      - name: Notify failure
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Take a lap to see what is real
        run: env

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name gh-actions-playground
