name: GH Actions Playground (with rust!!)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo hello from GH Actions

      - name: See if Rust build tools are present
        run: |
          echo cargo version:
          cargo --version

      - name: Build Rust tool
        run: cargo build --release

      - name: My backup step
        if: ${{ failure() }}
        run: echo build failed !!!!

      - name: Take a lap to see what is real
        run: env

      - name: Run this town
        run: ./target/release/gh-actions-playground --myvar=$VAR_1
